github.com:
    users:
        ShijoeBytesBric:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: ShijoeBytesBric
