# Application specific tweaks
source = ~/.config/hypr/apps/system.conf
source = ~/.config/hypr/apps/browser.conf
source = ~/.config/hypr/apps/geforce.conf
source = ~/.config/hypr/apps/steam.conf
source = ~/.config/hypr/apps/webcam-overlay.conf
