exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all

# swww daemon
exec-once = uwsm app -- swww-daemon --format argb
exec-once = bash -c 'sleep 1 && ~/.config/themes/switch-theme.sh $(cat ~/.local/share/themes/active-theme 2>/dev/null || echo dark)'

# waybar
exec-once = uwsm app -- waybar

# walker-launcher
exec-once = uwsm app -- elephant
exec-once = uwsm app -- walker --gapplication-service &

# hypridle
exec-once = uwsm app -- hypridle
