force_keyboard_focus = true                                                 # forces keyboard forcus to stay in Walker
selection_wrap = true                                                       # wrap list if at bottom or top
hide_action_hints = true                                                    # globally hide the action hints

[providers]
default = [
  "desktopapplications"
]

empty = ["desktopapplications"]  # Shown when query is empty
max_results = 50

[[providers.prefixes]]
prefix = "$"
provider = "clipboard"

[[emergencies]]
text = "Restart Walker"
command = "omarchy-restart-walker"
